In [1]:
import itertools
import numpy as np


def hamming_parity_check_matrix(m: int) -> np.ndarray:
    cols = []
    for x in range(1, 2**m):
        bits = [(x >> i) & 1 for i in range(m - 1, -1, -1)]
        cols.append(bits)
    return np.array(cols).T % 2


def generate_codewords(G: np.ndarray) -> np.ndarray:
    k, n = G.shape
    codewords = []

    for msg in itertools.product([0, 1], repeat=k):
        u = np.array(msg, dtype=int)
        c = (u @ G) % 2
        codewords.append(c)

    return np.array(codewords, dtype=int)


def hamming_weight(v: np.ndarray) -> int:
    return int(np.sum(v))


def hamming_distance(v1: np.ndarray, v2: np.ndarray) -> int:
    return int(np.sum((v1 + v2) % 2))


def verify_simplex(m: int):
    H = hamming_parity_check_matrix(m)
    G_dual = H.copy()

    codewords = generate_codewords(G_dual)

    n = 2**m - 1
    k = m
    expected_weight = 2**(m - 1)

    print(f"m = {m}")
    print(f"Ожидаемые параметры симплекс-кода: [{n}, {k}, {expected_weight}]")
    print("\nПорождающая матрица дуального кода (это H):")
    print(G_dual)

    print("\nВсе кодовые слова:")
    for i, c in enumerate(codewords):
        print(f"{i:2d}: {''.join(map(str, c))}   weight = {hamming_weight(c)}")

    nonzero_codewords = [c for c in codewords if np.any(c != 0)]
    weights = [hamming_weight(c) for c in nonzero_codewords]

    print("\nВеса всех ненулевых кодовых слов:")
    print(weights)

    all_weights_ok = all(w == expected_weight for w in weights)
    print(f"\nВсе ненулевые слова имеют вес {expected_weight}: {all_weights_ok}")

    distances = []
    all_dist_ok = True

    for i in range(len(codewords)):
        for j in range(i + 1, len(codewords)):
            d = hamming_distance(codewords[i], codewords[j])
            distances.append(d)
            if d != expected_weight:
                all_dist_ok = False

    print("\nПопарные расстояния между различными кодовыми словами:")
    print(distances)
    print(f"\nВсе расстояния равны {expected_weight}: {all_dist_ok}")

    if all_weights_ok and all_dist_ok:
        print("\nВывод: дуальный код к коду Хэмминга действительно является симплексным.")
    else:
        print("\nВывод: проверка не пройдена.")


verify_simplex(3)

m = 3
Ожидаемые параметры симплекс-кода: [7, 3, 4]

Порождающая матрица дуального кода (это H):
[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]

Все кодовые слова:
 0: 0000000   weight = 0
 1: 1010101   weight = 4
 2: 0110011   weight = 4
 3: 1100110   weight = 4
 4: 0001111   weight = 4
 5: 1011010   weight = 4
 6: 0111100   weight = 4
 7: 1101001   weight = 4

Веса всех ненулевых кодовых слов:
[4, 4, 4, 4, 4, 4, 4]

Все ненулевые слова имеют вес 4: True

Попарные расстояния между различными кодовыми словами:
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

Все расстояния равны 4: True

Вывод: дуальный код к коду Хэмминга действительно является симплексным.
